
/**Role Actions  */
export const GET_COUNT_SUCCESS = "GET_COUNT_SUCCESS";
export const GET_CARTITEMS_SUCCESS = "GET_CARTITEMS_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";